##############################
# --- USER CONFIGURATION --- #
##############################

title: White Oath
description: White Oath Exocore
url: https://whiteoath.net
repository: yenwhiteoath/exocore

##############################################
# --- ANALYTICS CONFIGURATION (OPTIONAL) --- #
##############################################

jekyll_analytics:        # Uncomment desired analytics tracker and input details
#  GoogleAnalytics:          # Uncomment section if you want to track with Google Analytics
#    id: UA-123-456          # Required - replace with your tracking id
#    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking

#  Matomo:                   # Uncomment section if you want to track with Matomo (former Piwik Analytics)
#    url: matomo.example.com # Required - url to Matomo installation without trailing /
#    siteId: "1234"          # Required - replace with your Matomo site id (Write id as string)

#  Piwik:                    # Uncomment section if you want to track with Piwik
#    url: piwik.example.com  # Required - url to Piwik installation without trailing /
#    siteId: "1234"          # Required - replace with your Piwik site id (Write id as string)

#  MPulse:                   # Uncomment section if you want to track performance with mPulse
#    apikey: XXXXX-YYYYY-ZZZZZ-AAAAA-23456   # Required - replace with your mPulse API key

#  Plausible:
#    domain: 'example.com'   # The domain configured in plausible
#    source: 'https://plausible.example.com/js/plausible.js' # The source of the javascript

#################################
# --- EXOCORE CONFIGURATION --- #
#################################

baseurl: '' 
source: .
destination: _site
background: "red"
highlighter: rouge
permalink: /:categories/:slug/

gist:
  noscript: false

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

readme_index:
  enabled: true

sass:
    sass_dir: ./exocore/_sass

layouts_dir: ./exocore/_layouts
includes_dir: ./exocore/_includes
plugins_dir: ./exocore/_plugins
data_dir: ./exocore/data
      
defaults:
  - scope:
      path: "" 
    values:
      layout: "default"
      date: "Jan 1 2000"
  - scope:
      path: ""
    values:
      image: /assets/imgs/card.jpg
  - scope:
      path: ""
      type: "articles"
    values: 
      layout: "article"
  - scope:
      path: ""
      type: "journal"
    values: 
      layout: "journal"
  - scope:
      path: ""
      type: "wiki"
    values: 
      layout: "wiki"
  - scope:
      path: ""
      type: "daily"
    values: 
      layout: "daily"
  - scope:
      path: ""
      type: "scrapbook"
    values: 
      layout: "scrapbook"


collections:

  wiki:
    output: true
    
  journal:
    output: true
    
  articles:
    output: true

  daily:
    output: true

  scrapbook:
    output: true

relative_links:
  enabled:     true
  collections: true
  
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true
    
graphviz:
  options: "-Tsvg" # 'dot' command option
  command: "dot"   # execute this string. specify full path to 'dot' if you need


plugins:
- jekyll-optional-front-matter
- jekyll-readme-index
- jekyll-default-layout
- jekyll-titles-from-headings
- jekyll-relative-links
- jekyll-github-metadata
- jekyll-seo-tag
- html-proofer
- rubocop
- w3c_validators
- jekyll-last-modified-at
- jekyll-redirect-from
- jekyll-feed
- jekyll-wikilinks
- ruby-graphviz